server:
  context-path: /
spring:
  thymeleaf:
    cache: false
  application:
    admin:
      enabled: true
      jmx-name: org.springframework.boot:type=Admin,name=SpringApplication
  profiles:
    active: dev