server:
  context-path: /
spring:
  thymeleaf:
    cache: false
  application:
    admin:
      enabled: true
      jmx-name: org.springframework.boot:type=Admin,name=SpringApplication
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
  type-aliases-package: com.jsen.blog.study.mybatis